server:
  port: 3344
spring:
  application:
    name: cloud-config-center   # 注册进eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RoyalNG945/springcloud-config.git   #github上面的git仓库地址
          search-paths:
            - springcloud-config    #搜索目录
      label: master   # 读取分支
#  服务注册到eureka的 地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
# rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# rabbitmq相关配置 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"



